auto:             true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Chuge
url:              http://chuge.github.com
feed:             /atom.xml
author:
    name:         Chuge
    twitter:      none
description:      "Chuge\'s Blog"
author_info:      <a href="http://chuge.github.com/about">Chuge</a>

copyright:
    - Design by <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; Copyright 2012
